### ISSUE TITLE
mqtt_bridge not available

### ISSUE THREAD

**Issue by iaherzog** [robocup-logistics/rcll-get-started#3]
I tried to start the mqtt-bridge with the rcll-get-started repo. The following two problems occurred:

First, the function `mqtt_bridge` is not defined. I guess, the ENV variable `RC_MQTT_START` should be set to `true` in the `local_setup.sh`. 

Second, even when I'm logged into ghcr.io, I get an 'access denied' error when trying to pull mqtt. Is it set to private?

**Comment by pkohout** [comment]
Hi,
ups there were some pending changes on my laptop, I updated the README and the setup. now there is a `rc_start_mqtt_bridge` and `rc_stop_mqtt_bridge`.

Yes once you set `RC_MQTT_START` it is automatically started once you start the refbox. Note that if you stop the refbox by pressing CTRL + C its not stopping the mqtt bridge, but using rc_stop_refbox works.

Yes indeed the package is private, @TarikViehmann can you change the settings in the robocup-logistics organization so that we can make this public.
![image](https://github.com/robocup-logistics/rcll-get-started/assets/5959988/0aac8f25-0962-41cf-b990-018aacd3ebbc)

@iaherzog  I will add you to the [mqtt-bridge](https://github.com/robocup-logistics/rcll-mqtt-bridge) then you should be able to use it already.

**Comment by pkohout** [comment]
@iaherzog  you should have a pending invite, as soon as you accept that it I guess you should be able to download the image. Otherwise please let me know.

**Comment by TarikViehmann** [comment]
okay, the organization now allows public packages

**Comment by iaherzog** [comment]
Thank you @pkohout and @TarikViehmann for fixing this issue so quickly.
